spring:
  main:
    web-application-type: reactive
  application:
    name: auth-service
  cloud:
    gateway:
      routes:
        - id: order-service # 라우트 식별자
          uri: lb://order-service # 'order-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/orders/** # /orders 이하 모든 url
        - id: product-service # 라우트 식별자
          uri: lb://product-service # 'product-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/products/** # /products 이하 모든 url
        - id: auth-service  # 라우트 식별자
          uri: lb://auth-service  # 'auth-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/auth/** # /auth 이하 모든 url
      discovery:
        locator:
          enabled: true

# 서버 포트 19091으로 설정
server:
  port: 19091

# eureka client 로 등록
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# Jwt secret-key 등록
service:
  jwt:
    access-expiration: 3600000
    secret-key: "432bd1e37390834c1e93041938d64478979886f397a782535780e357c15846731671543df8448946958f58cd2effb694a50f55e9120c3f7ad4f6b131973de0d1a89c00a1397a4c03d90f15dc31543659e9d43990eb04e5a2c84d8b4b5df1d902a3090d383027ce5199f2aa82723f5154ff4b80b19b6a46274aff1de7bc14daf1a1b801f52b662a70369c84558b9d265ba0788a3aa0ecc1f7778384aad95416a5d2f1ab0270d539b5649d137333a0a8955ffdb9d3537bcb9d09888d7d4979bff84515bf9aebd1e2b5071195f47f374faf42b6506f35344e9cb9f5fd5daf0c16dbfe5cd2d11891c820e9dd3d2af9f7147184d0958f80ada089c97187404a9aa2c4"
